test_prefix_arr:
	g++ -O2 -g -Wall -Wextra prefix_array.cpp -o prefix_array && ./prefix_array
test_prefix_matrix:
	g++ -O2 -g -Wall -Wextra prefix_matrix.cpp -o prefix_matrix && ./prefix_matrix
test_xor_arr:
	g++ -O2 -g -Wall -Wextra xor_arr.cpp -o xor_arr && ./xor_arr